import { BloomScreen } from '@/types/index';

export const SAMPLE_SCREEN: BloomScreen = {
  id: 'screen-1',
  name: 'Product Showcase',
  components: [
    {
      id: 'container-1',
      type: 'container',
      label: 'Header',
      styles: {
        display: 'flex',
        flexDirection: 'column',
        gap: '20px',
        padding: '40px 24px',
        backgroundColor: '#f8f9fa',
        borderRadius: '0px',
      },
      children: [
        {
          id: 'heading-1',
          type: 'heading',
          label: 'Main Title',
          content: 'Welcome to Bloom',
          styles: {
            fontSize: '32px',
            fontWeight: '700',
            fontFamily: 'Inter',
            color: '#1a1a1a',
            textAlign: 'center',
            margin: '0px',
            lineHeight: '1.2',
          },
        },
        {
          id: 'text-1',
          type: 'text',
          label: 'Subtitle',
          content: 'Create beautiful, interactive interfaces with AI-powered design tools',
          styles: {
            fontSize: '16px',
            fontWeight: '400',
            fontFamily: 'Inter',
            color: '#666666',
            textAlign: 'center',
            margin: '0px',
            lineHeight: '1.6',
          },
        },
      ],
    },
    {
      id: 'container-2',
      type: 'container',
      label: 'Cards Grid',
      styles: {
        display: 'flex',
        flexDirection: 'row',
        gap: '24px',
        padding: '40px 24px',
        justifyContent: 'space-around',
        alignItems: 'flex-start',
      },
      children: [
        {
          id: 'card-1',
          type: 'card',
          label: 'Feature Card 1',
          styles: {
            display: 'flex',
            flexDirection: 'column',
            gap: '16px',
            padding: '24px',
            backgroundColor: '#ffffff',
            borderRadius: '12px',
            border: '1px solid #e5e7eb',
            boxShadow: '0 1px 3px rgba(0,0,0,0.1)',
            width: '280px',
            minHeight: '200px',
          },
          children: [
            {
              id: 'heading-2',
              type: 'heading',
              content: '⚡ Fast Design',
              styles: {
                fontSize: '18px',
                fontWeight: '600',
                color: '#1a1a1a',
                margin: '0px',
              },
            },
            {
              id: 'text-2',
              type: 'text',
              content: 'Design components at lightning speed with real-time preview and instant feedback.',
              styles: {
                fontSize: '14px',
                color: '#666666',
                lineHeight: '1.5',
                margin: '0px',
              },
            },
          ],
        },
        {
          id: 'card-2',
          type: 'card',
          label: 'Feature Card 2',
          styles: {
            display: 'flex',
            flexDirection: 'column',
            gap: '16px',
            padding: '24px',
            backgroundColor: '#ffffff',
            borderRadius: '12px',
            border: '1px solid #e5e7eb',
            boxShadow: '0 1px 3px rgba(0,0,0,0.1)',
            width: '280px',
            minHeight: '200px',
          },
          children: [
            {
              id: 'heading-3',
              type: 'heading',
              content: '🎨 Beautiful Defaults',
              styles: {
                fontSize: '18px',
                fontWeight: '600',
                color: '#1a1a1a',
                margin: '0px',
              },
            },
            {
              id: 'text-3',
              type: 'text',
              content: 'Pre-built components with modern design patterns and accessibility built-in.',
              styles: {
                fontSize: '14px',
                color: '#666666',
                lineHeight: '1.5',
                margin: '0px',
              },
            },
          ],
        },
        {
          id: 'card-3',
          type: 'card',
          label: 'Feature Card 3',
          styles: {
            display: 'flex',
            flexDirection: 'column',
            gap: '16px',
            padding: '24px',
            backgroundColor: '#ffffff',
            borderRadius: '12px',
            border: '1px solid #e5e7eb',
            boxShadow: '0 1px 3px rgba(0,0,0,0.1)',
            width: '280px',
            minHeight: '200px',
          },
          children: [
            {
              id: 'heading-4',
              type: 'heading',
              content: '🔄 Export Ready',
              styles: {
                fontSize: '18px',
                fontWeight: '600',
                color: '#1a1a1a',
                margin: '0px',
              },
            },
            {
              id: 'text-4',
              type: 'text',
              content: 'Export your designs as clean JSON for seamless integration into your projects.',
              styles: {
                fontSize: '14px',
                color: '#666666',
                lineHeight: '1.5',
                margin: '0px',
              },
            },
          ],
        },
      ],
    },
    {
      id: 'container-3',
      type: 'container',
      label: 'CTA Section',
      styles: {
        display: 'flex',
        flexDirection: 'column',
        gap: '16px',
        padding: '40px 24px',
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: '#f0f4ff',
        borderRadius: '0px',
      },
      children: [
        {
          id: 'heading-5',
          type: 'heading',
          content: 'Ready to get started?',
          styles: {
            fontSize: '28px',
            fontWeight: '700',
            color: '#1a1a1a',
            margin: '0px 0px 16px 0px',
            textAlign: 'center',
          },
        },
        {
          id: 'button-1',
          type: 'button',
          label: 'CTA Button',
          content: 'Start Creating',
          styles: {
            padding: '12px 32px',
            backgroundColor: '#4f46e5',
            color: '#ffffff',
            fontSize: '16px',
            fontWeight: '600',
            borderRadius: '8px',
            border: 'none',
            boxShadow: '0 2px 8px rgba(79,70,229,0.3)',
          },
        },
      ],
    },
  ],
  metadata: {
    createdAt: new Date().toISOString(),
    description: 'Sample product showcase screen for Bloom interactive playground',
  },
};
